# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60ddda7a3a4f81b908ba6a32c13827cce19f3de1fe4eb6f4495d2c4665f1311447f2aeeb8270d38bee0dc473ac7dfa99c68af7877066dae8de4416ac563a7794

test:
  secret_key_base: 5d8434417d135ef02d7cd57b0b7fa8c20f9506e4817c3d88d1da250c9bbba1affd2724cffa73488e7eb7ad1108278eba4173ffa231b9dc3fc9ff48943a1daead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
